'use client'

import { useEffect, useState, type ComponentType, type ReactNode } from 'react'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {
  decodeShareFragment,
  isShareLinkExpired,
  isShareLinkBurned,
  markShareLinkBurned,
} from '@/utils/shareLink'
import { remarkCallouts } from '@/utils/remarkCallouts'
import { CALLOUT_TYPES, type CalloutType } from '@/utils/callouts'
import { CalloutBox } from '@/components/shared/CalloutBox'

// remarkCallouts tags a `> [!NOTE]`-style blockquote's hast node with
// `data-callout`; render those as a CalloutBox for parity with the in-app
// preview and with github.com's own rendering.
const ShareBlockquote = (({ children, ...rest }: { children?: ReactNode; [key: string]: unknown }) => {
  const calloutAttr = rest['data-callout']
  const calloutType = typeof calloutAttr === 'string' && (CALLOUT_TYPES as string[]).includes(calloutAttr)
    ? (calloutAttr as CalloutType)
    : null
  if (calloutType) return <CalloutBox type={calloutType}>{children}</CalloutBox>
  return <blockquote>{children}</blockquote>
}) as ComponentType<unknown>

// Read-only viewer for a shared note. The note content is encoded in the
// URL hash fragment (`/share#<b64>`); we decode on mount + render as
// markdown. Hash fragments never reach the server, so the content is
// only visible to whoever has the link.

interface DecodedNote {
  title: string
  content: string
  ts: number
}

export default function SharePage() {
  const [note, setNote] = useState<DecodedNote | null>(null)
  const [fragment, setFragment] = useState<string>('')
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    // Wrapped in an async IIFE because the burn-after-read helpers
    // call crypto.subtle.digest under the hood, which is async.
    let cancelled = false
    ;(async () => {
      const frag = window.location.hash.slice(1)
      if (cancelled) return
      setFragment(frag)
      if (!frag) {
        setError('No content found in the link. Make sure you copied the full URL including everything after the # symbol.')
        return
      }
      const decoded = decodeShareFragment(frag)
      if (!decoded) {
        setError('This share link is invalid or was generated by an incompatible version.')
        return
      }
      // shr2: enforce client-side expiry. Honor-system check — a
      // recipient who tampers with their clock can bypass, but for
      // routine "this link should stop working" UX it's enough.
      if (isShareLinkExpired(decoded)) {
        const when = decoded.expiresAt
          ? new Date(decoded.expiresAt).toLocaleString()
          : 'a past date'
        setError(`This share link expired on ${when}.`)
        return
      }
      // shr2: enforce burn-after-read. The recipient browser stores a
      // tombstone keyed on a SHA-256 hash of the fragment so a revisit
      // refuses even if the user copy-pasted the URL into a new tab.
      // Doesn't protect against multiple devices opening the same URL
      // — that's the inherent limit of a backend-less share.
      if (decoded.burn) {
        if (await isShareLinkBurned(frag)) {
          if (cancelled) return
          setError('This was a single-view share link and has already been opened.')
          return
        }
        // Mark burned BEFORE rendering so a clipboard-API failure or a
        // crash doesn't leave the link reusable.
        await markShareLinkBurned(frag)
      }
      if (cancelled) return
      setNote({ title: decoded.title, content: decoded.content, ts: decoded.ts })
      document.title = `${decoded.title} — Shared via Noteser`
    })()
    return () => { cancelled = true }
  }, [])

  if (error) {
    return (
      <div className="min-h-screen bg-obsidianBlack text-obsidianText flex items-center justify-center p-8">
        <div className="max-w-md text-center space-y-4">
          <h1 className="text-2xl font-medium">Couldn&apos;t open this note</h1>
          <p className="text-obsidianSecondaryText">{error}</p>
          <Link href="/" className="inline-block px-4 py-2 bg-obsidianAccentPurple/20 text-obsidianAccentPurple rounded hover:bg-obsidianAccentPurple/30">
            Go to Noteser
          </Link>
        </div>
      </div>
    )
  }

  if (!note) {
    return (
      <div className="min-h-screen bg-obsidianBlack text-obsidianSecondaryText flex items-center justify-center">
        <div>Decoding…</div>
      </div>
    )
  }

  const generatedDate = new Date(note.ts).toLocaleDateString(undefined, {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  return (
    <div className="min-h-screen bg-obsidianBlack text-obsidianText">
      <header className="border-b border-obsidianBorder px-6 py-4 flex items-center justify-between bg-obsidianBlack/80 backdrop-blur sticky top-0 z-10 gap-4">
        <div className="min-w-0">
          <div className="text-xs text-obsidianSecondaryText">Shared via Noteser · {generatedDate}</div>
          <h1 className="text-xl font-medium truncate">{note.title}</h1>
        </div>
        <div className="flex items-center gap-2 flex-none">
          {/* Import passes the same fragment through to the main app — it
              decodes + adds the note + opens it. Hash fragments stay
              client-side so the payload never touches the server. */}
          <Link
            href={`/?import=${encodeURIComponent(fragment)}`}
            data-testid="share-import-cta"
            className="text-sm px-3 py-1.5 bg-obsidianAccentPurple text-white rounded hover:bg-obsidianAccentPurple/85 transition-colors"
          >
            Import to my vault
          </Link>
          <Link
            href="/"
            className="text-sm px-3 py-1.5 bg-obsidianAccentPurple/15 text-obsidianAccentPurple border border-obsidianAccentPurple/40 rounded hover:bg-obsidianAccentPurple/25 transition-colors"
          >
            Open Noteser →
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-8">
        <article className="prose prose-invert max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm, remarkCallouts]} components={{ blockquote: ShareBlockquote }}>
            {note.content || '*This note is empty.*'}
          </ReactMarkdown>
        </article>
      </main>
      <footer className="border-t border-obsidianBorder px-6 py-4 text-xs text-obsidianSecondaryText text-center">
        Read-only view. The content lives in the URL — anyone with this link can read it.
      </footer>
    </div>
  )
}
