/**
 * Per-request Content-Security-Policy builder. Finding 6 of the 2026-05-21
 * security audit: the old CSP shipped a *static* header with
 * `script-src 'self' 'unsafe-inline'`, which defeats the purpose of a CSP —
 * an injected inline <script> would execute. We replace it with a
 * per-request nonce emitted from middleware (`src/middleware.ts`):
 *
 *   script-src 'self' 'nonce-<random>' 'strict-dynamic'
 *
 * `'strict-dynamic'` lets Next's nonced bootstrap scripts load the rest of
 * the bundle without us having to enumerate every chunk URL; modern browsers
 * then ignore the `'self'` host-source fallback, so 'self' is kept only for
 * the (legacy) browsers that don't understand 'strict-dynamic'.
 *
 * 'unsafe-eval' is added ONLY in non-production (Next dev HMR / React
 * Refresh). Production drops it: React/Next ship no eval in their prod
 * bundles and the CodeMirror stack we use does not construct Functions at
 * runtime, so dropping it neutralises eval-based XSS even if an injection
 * slips through.
 *
 * style-src keeps 'unsafe-inline' on purpose — Tailwind, styled-jsx and
 * CodeMirror (EditorView.baseTheme) all inject inline <style>. Nonce-ing
 * styles would break the editor and the whole theme, so we do not.
 */

/**
 * Derive a single WS origin from a raw NEXT_PUBLIC_YJS_WS_URL value so the
 * CSP only allows the collaboration server the operator opted into. Anything
 * malformed (or unset) collapses to `null` ("no WS connections at all") —
 * the bare `wss: ws:` wildcards (Finding 5) would let an XSS payload
 * exfiltrate localStorage to any host.
 */
export function deriveCollabWsOrigin(raw: string | undefined): string | null {
  if (!raw) return null
  try {
    const url = new URL(raw)
    if (url.protocol !== 'ws:' && url.protocol !== 'wss:') return null
    return `${url.protocol}//${url.host}`
  } catch {
    return null
  }
}

/**
 * Derive a single http(s) origin from a raw NEXT_PUBLIC_FORGEJO_BASE_URL
 * value so the CSP only allows the self-hosted Forgejo/Gitea instance the
 * operator opted into at deploy time. Same posture as deriveCollabWsOrigin:
 * an allow-listed origin, never a scheme wildcard — a runtime-controllable
 * connect-src would let an XSS payload exfiltrate localStorage (which holds
 * the git token) to an arbitrary host. Codeberg itself is a static entry in
 * connect-src and needs no env var.
 */
export function deriveGitHostOrigin(raw: string | undefined): string | null {
  if (!raw) return null
  try {
    const url = new URL(raw)
    if (url.protocol !== 'http:' && url.protocol !== 'https:') return null
    return `${url.protocol}//${url.host}`
  } catch {
    return null
  }
}

export interface BuildCspOptions {
  /** Non-production (dev / test): adds 'unsafe-eval' to script-src. */
  isDev: boolean
  /** Already-derived ws(s):// origin to add to connect-src, or null. */
  wsOrigin: string | null
  /** Already-derived self-hosted Forgejo origin for connect-src, or null. */
  gitHostOrigin?: string | null
  /**
   * Drop the `https:` wildcard from img-src. The editor's own notes
   * legitimately embed arbitrary HTTPS images (`![]()`), but the public
   * `/share` page renders content from a URL fragment that can come from
   * anyone with the link — a remote `<img>` there doubles as a tracking
   * pixel (confirms the link was opened, leaks the viewer's IP/UA to the
   * image host). Defaults to false so every other route is unaffected.
   */
  restrictImages?: boolean
}

/**
 * Build the full CSP header value for a single request.
 *
 * @param nonce base64 per-request nonce (already generated by middleware).
 */
export function buildCsp(nonce: string, options: BuildCspOptions): string {
  const { isDev, wsOrigin, gitHostOrigin = null, restrictImages = false } = options

  const scriptSrc = [
    "'self'",
    `'nonce-${nonce}'`,
    "'strict-dynamic'",
    ...(isDev ? ["'unsafe-eval'"] : []),
  ].join(' ')

  const connectSrc = [
    "'self'",
    'https://api.github.com',
    'https://github.com',
    // Codeberg is the built-in Forgejo host preset in the vault connect flow;
    // its Gitea API is called browser-direct just like api.github.com.
    'https://codeberg.org',
    'https://api.anthropic.com',
    'https://api.openai.com',
    ...(wsOrigin ? [wsOrigin] : []),
    // Self-hosted Forgejo/Gitea: only the single origin the operator
    // allow-listed via NEXT_PUBLIC_FORGEJO_BASE_URL (see deriveGitHostOrigin).
    ...(gitHostOrigin ? [gitHostOrigin] : []),
  ].join(' ')

  return [
    "default-src 'self'",
    `script-src ${scriptSrc}`,
    // Keep 'unsafe-inline' for styles: Tailwind / styled-jsx / CodeMirror
    // all inject inline <style>. Do NOT nonce styles.
    "style-src 'self' 'unsafe-inline'",
    // User notes can ![]() any HTTPS image. data:/blob: for attachments.
    // On /share, arbitrary HTTPS images are dropped (see restrictImages
    // above) so a shared link can't be turned into a tracking pixel.
    `img-src 'self' data: blob:${restrictImages ? '' : ' https:'}`,
    "font-src 'self' data:",
    // Browser-direct API surfaces: github.com for OAuth fallbacks, the
    // GitHub Git Data API, Anthropic + OpenAI for BYO-key AI features.
    // The optional Yjs collab server is added only when
    // NEXT_PUBLIC_YJS_WS_URL is a valid ws:// or wss:// URL.
    `connect-src ${connectSrc}`,
    // PWA: the service worker (public/sw.js) is same-origin, so 'self' is
    // enough; the register() call itself is nonced app JS. The web app
    // manifest is also same-origin.
    "worker-src 'self'",
    "manifest-src 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "object-src 'none'",
  ].join('; ')
}
